### ISSUE TITLE
Add burn tax info to all views that require it

### ISSUE THREAD

**Issue by MarventusWP** [terra-rebels/finder#1]
WHAT: Show burn tax payed for every TX on all views that require it
WHY: Show end users that the tax was actually implemented
WHO: Classic Network end users

**Tasks:**
- [ ] Add 1.2% burn tax column with the amount collected to the wallet view
- [ ] Add 1.2% burn tax column with the amount collected to the single TX view
- [ ] Check what other views would need to display the burn tax info

**Acceptance criteria/Definition of Done:**
- [ ] All relevant areas and views of the finder are showing the correct burn tax amount
