### ISSUE TITLE
Show burn tax column in all views

### ISSUE THREAD

**Issue by MarventusWP** [terra-rebels/finder#10]
WHAT: Show burn tax payed for all necessary views
WHY: Show end users that the tax was actually implemented
WHO: Classic Network end users

**Tasks:**
- [ ] Add 1.2% burn tax information to all components or views that require it.
- [ ] Check what other views would need to display the burn tax info.
- [ ] Ensure the tax becomes visible for the following TX types: MsgSend, MsgExec,
MsgMultiSend, MsgSwapSend, MsgInstantiateContract, MsgExecuteContract.
- [ ] Test code changes on rebel-1 and classic networks.

**Acceptance criteria:**
- [ ] All necessary views of the platform should show the correct burn tax amount.
